# Generated by Django 5.1.1 on 2024-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_role',
            field=models.CharField(choices=[('gamer', 'Gamer'), ('creator', 'Creator'), ('event_organizer', 'Event Organizer')], default='gamer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gaming_usernames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
